

List<Object> AllEnglishSpells = [
  {'classID': 1,
    'spells': {//战士
      'devastate': '毁灭打击',
      'shield_slam': '盾牌猛击',
      'revenge': '复仇',
      'execute': '斩杀',
      'storm_bolt': '风暴之锤',
      'dragon_roar': '巨龙怒吼',
      'rage': '怒气',
      'thunder_clap': '雷霆一击',
      'bladestorm': '剑刃风暴',
      'deep_wounds': '重伤',
      'sudden_death': '猝死',
      'unyielding_strikes': '不屈打击',
      'bloodbath': '血之气息',
    }
  }, {
    'classID': 2,
    'spells': {//圣骑士
      'speed_of_light': '圣光之速',
      'judgment': '审判',
      'empowered_seals': '强化圣印',
      'execution_sentence': '处决宣判',
      'lights_hammer': '圣光之锤',
      'avenging_wrath': '复仇之怒',
      'holy_avenger': '神圣复仇者',
      'seraphim': '炽天使',
      'divine_storm': '神圣风暴',
      'final_verdict': '最终审判',
      'templars_verdict': '圣殿骑士的裁决',
      'hammer_of_wrath': '愤怒之锤',
      'exorcism': '驱邪术',
      'seal_of_truth': '真理圣印',
      'seal_of_righteousness': '正义圣印',
      'crusader_strike': '十字军打击',
      'glyph': '雕文',
      'holy_prism': '神圣棱镜',
      'hammer_of_the_righteous': '正义之锤',
      'divine_protection': '圣佑术',
      'guardian_of_ancient_kings': '远古列王守卫',
      'ardent_defender': '炙热防御者',
      'shield_of_the_righteous': '正义盾击',
      'eternal_flame': '永恒之火',
      'divine_purpose': '神圣意志',
      'seal_of_insight': '洞察圣印',
      'avengers_shield': '复仇者之盾',
      'grand_crusader': '大十字军',
      'holy_wrath': '神圣愤怒',
      'sanctified_wrath': '圣洁怒火',
      'consecration': '奉献',
      'sacred_shield': '圣洁护盾',
      'flash_of_light': '圣光闪现',
      'selfless_healer': '无私治愈',
      'maraads_truth': '玛尔拉德的真理（真理圣印）',
      'liadrins_righteousness': '莉亚德林的公正(正义圣印)',
      'double_jeopardy': '双重审判',
      'final_wrath': '终结怒火',
      'seal.truth': '真理圣印',
      'seal.righteousness': '正义圣印',
      'divine_crusader': '神圣十字军',
    }
  }, {
    'classID': 3,
    'spells': {//猎人
      'cobra_shot': '眼镜蛇射击',
      'dire_beast': '凶暴野兽',
      'bestial_wrath': '狂野怒火',
      'barrage': '弹幕射击',
      'multishot': '多重射击',
      'a_murder_of_crows': '夺命黑鸦',
      'kill_shot': '夺命射击',
      'kill_command': '杀戮命令',
      'glaive_toss': '飞刃',
      'powershot': '强风射击',
      'arcane_shot': '奥术射击',
      'stampede': '群兽奔腾',
      'explosive_trap': '爆炸陷阱',
    }
  }, {
    'classID': 4,
    'spells': {//盗贼
      'throw': '投掷', //121733,
      'ritualofsacrifice': '影袭', //1752,
      'eviscerate': '刺骨', //2098,
      'stealth': '潜行', //1784,
      'ambush': '伏击', //8676,
      'shadowward': '闪避', //5277,
      'dualweild': '致命药膏', //2823,
      'lsap': '闷棍', //6770,
      'slice_and_dice': '切割', //5171,
      'inv_misc_bag_11': '搜索', //921,
      'recuperate': '恢复', //73651,
      'kick': '脚踢', //1766,
      'poisonsting': '减速药膏', //3408,
      'gouge': '凿击', //1776,
      'moonkey': '开锁', //1804,
      'sprint': '疾跑', //2983,
      'nullifydisease': '麻痹药膏', //5761,
      'distract': '扰乱', //1725,
      'inv_misc_herb_16': '致伤药膏', //8679,
      'cheapshot': '偷袭', //1833,
      'vanish': '消失', //1856,
      'riposte': '破甲', //8647,
      'mindsteal': '致盲', //2094,
      'kidneyshot': '肾击', //408,
      'feint': '佯攻', //1966,
      'rupture': '割裂', //1943,
      'garrote': '锁喉', //703,
      'dismantle': '拆卸', //51722,
      'grimward': '解除陷阱', //1842,
      'nethercloak': '暗影斗篷', //31224,
      'fan_of_knives': '刀扇', //51723,
      'preparation': '伺机待发', //14185,
      'envelopingshadows': '暗遁', //114842,
      'inv_throwingknife_04': '毒刃', //5938,
      'shroudofconcealment': '潜伏帷幕', //114018,
      'tricksofthetrade': '嫁祸诀窍', //57934,
      'redirect': '转嫁', //73981,
      'crimson_tempest': '猩红风暴', //121411,
      'smoke': '烟雾弹', //76577,
      'inv_knife_1h_grimbatolraid_d_03': '暗影之刃', //121471,
      'mutilate': '毁伤', //1329,
      'envenom': '毒伤', //32645,
      'backstab': '斩击', //111240,
      'vendetta': '仇杀', //79140,
      'punishingblow': '剑刃乱舞', //13877,
      'inv_sword_97': '要害打击', //84617,
      'shadowworddominate': '冲动', //13750,
      'murderspree': '杀戮盛筵', //51690,
      'lifedrain': '出血', //16511,
      'possession': '预谋', //14183,
      'dispatch': '背刺', //53,
      'shadowdance': '暗影之舞', //51713,
      'inv_throwingknife_06': '致命投掷', //26679,
      'combatreadiness': '备战就绪', //74001,
      'leeching_poison': '吸血药膏', //108211,
      'shadowstep': '暗影步', //36554,
      'burstofspeed': '速度爆发', //108212,
      'paralytic_poison': '瘫痪药膏', //108215,
      'inv_throwingknife_07': '飞镖投掷', //114014,
      'marked_for_death': '死亡标记', //137619,
      'virmens_bite': '兔妖之噬',
      'killing_spree': '杀戮盛宴',
      'adrenaline_rush': '冲动',
      'anticipation': '预感',
      'shadow_focus': '暗影集中',
      'subterfuge': '诡诈',
      'shadow_reflection': '暗影反射',
      'bandits_guile': '刺客的狡诈',
    }
  }, {
    'classID': 5,
    'spells': {//牧师
      'shadowform': '暗影形态',
      'potion': '合剂',
      'clarity_of_power': '透彻之力',
      'insanity': '疯狂',
      'void_entropy': '虚空熵能',
      'dispersion': '虚无',
      'mindbender': '摧心魔',
      'shadowfiend': '暗影魔',
      'shadow_word_death': '暗言术：灭',
      'mind_blast': '心灵震爆',
      'glyph': '雕文',
      'devouring_plague': '噬灵疫病',
      'surge_of_darkness': '黑暗涌动',
      'mind_harvest': '心灵收割',
      'halo': '光晕',
      'cascade': '瀑流',
      'divine_star': '神圣之星',
      'shadow_word_pain': '暗言术：痛',
      'auspicious_spirits': '吉兆',
      'vampiric_touch': '吸血鬼之触',
      'mind_spike': '心灵尖刺',
      'mind_sear': '精神灼烧',
      'mind_flay': '精神鞭笞',
      'shadowy_insight': '暗影洞察',
      'power_infusion': '能量灌注',
      'lightwell': '光明之泉',
      'power_word_solace': '真言术：慰',
      'prayer_of_mending': '愈合祷言',
      'divine_insight': '神圣洞察',
      'flash_heal': '快速治疗',
      'surge_of_light': '圣光涌动',
      'circle_of_healing': '治疗之环',
      'renew': '恢复',
      'heal': '治疗术',
      'serendipity': '妙手回春',
      'power_word_shield': '真言术：盾',
      'penance': '苦修',
      'borrowed_time': '争分夺秒',
    }
  }, {
    'classID': 6,
    'spells': {//死亡骑士
      'conversion': '符能转换',
      'lichborne': '巫妖之躯',
      'death_strike': '灵界打击',
      'army_of_the_dead': '亡者大军',
      'bone_shield': '白骨之盾',
      'dancing_rune_weapon': '符文刃舞',
      'icebound_fortitude': '冰封之韧',
      'vampiric_blood': '吸血鬼之血',
      'rune_tap': '符文分流',
      'death_pact': '天灾契约',
      'outbreak': '爆发',
      'necrotic_plague': '死疽',
      'death_coil': '凋零缠绕',
      'plague_strike': '暗影打击',
      'blood_plague': '血之疫病',
      'icy_touch': '冰冷触摸',
      'frost_fever': '冰霜疫病',
      'soul_reaper': '灵魂收割',
      'defile': '亵渎',
      'empower_rune_weapon,': '符文武器强化',
      'blood_boil': '血沸',
      'blood_tap': '活力分流',
      'disease': '疾病',
      'draenic_armor': '德拉诺护甲',
      'antimagic_shell': '反魔法护罩',
      'breath_of_sindragosa': '辛达苟萨吐息',
      'summon_gargoyle': '召唤石像鬼',
      'dark_transformation': '黑暗突变',
      'death_and_decay': '枯萎凋零',
      'scourge_strike': '天灾打击',
      'sudden_doom': '末日突降',
      'plague_leech': '吸血瘟疫',
      'empower_rune_weapon': '符文武器增效',
      'unholy_blight': '邪恶虫群',
      'festering_strike': '脓疮打击',
      'deaths_advance': '死亡脚步',
      'howling_blast': '凛风冲击',
      'frost_strike': '冰霜打击',
      'blood_charge': '鲜血充能',
      'killing_machine': '杀戮机器',
      'obliterate': '湮没',
      'pillar_of_frost': '冰霜之柱',
    }
  }, {
    'classID': 7,
    'spells': {//萨满

    }
  }, {
    'classID': 8,
    'spells': {//法师
      'rune of power': '能量符文',
      'ice floes': '浮冰',
      'prismatic_crystal': '幻灵晶体',
      'fireball': '火球',
      'mirror_image': '镜像',
      'meteor': '流星',
      'pyroblast': '炎爆术',
      'ignite': '点燃',
      'combustion': '燃烧',
      'inferno_blast': '炼狱冲击',
      'incanters_flow': '咒术洪流',
      'living_bomb': '活体炸弹',
      'blast_wave': '冲击波',
      'cold_snap': '急速冷却',
      'dragons_breath': '龙息术',
      'flamestrike': '烈焰风暴',
      'scorch': '灼烧',
      'Combustion': '燃烧',
      'duration': '持续',
      'LB': '活体',
      'UM': '不稳',
      'BW': '冲击波',
      'MI': '影像',
      'RoP': '法阵',
      'IF': '洪流',
      'Kind': '薪火',
      'PC': '水晶',
      'Met': '陨石',
      'counterspell': '法术法制',
      'blink': '闪现',
      'blazing_speed': '炽热疾速',
      'time_warp': '时间扭曲',
      'ice_floes': '浮冰',
      'rune_of_power': '能量符文',
      'presence_of_mind': '气定神闲',
      'spell_haste': '技能急速',
      'evocation': '唤醒',
      'arcane_power': '奥术强化',
      'arcane_charge': '奥术充能',
      'nether_tempest': '虚空风暴',
      'potion': '合剂',
      'trinket': '饰品',
      'supernova': '超级新星',
      'arcane_barrage': '奥术弹幕',
      'arcane_orb': '奥术宝珠',
      'cone_of_cold': '冰锥术',
      'arcane_explosion': '魔爆术',
      'arcane_missiles': '奥术飞弹',
      'set_bonus.tier17_4pc': 'T17四件套',
      'arcane_instability': '不稳定的奥术',
      'arcane_blast': '奥术冲击',
      'overpowered': '超强能量',
    }
  }, {
    'classID': 9,
    'spells': {//术士

    }
  }, {
    'classID': 10,
    'spells': {//武僧

    }
  }, {
    'classID': 11,
    'spells': {//德鲁伊
      'bristling_fur': '鬃毛倒竖',
      'maul': '重殴',
      'tooth_and_claw': '尖牙与利爪',
      'berserk': '狂暴',
      'frenzied_regeneration': '狂暴回复',
      'cenarion_ward': '塞纳里奥结界',
      'renewal': '新生',
      'heart_of_the_wild': '野性之心',
      'rejuvenation': '回春术',
      'natures_vigil': '自然的守护',
      'healing_touch': '治疗之触',
      'dream_of_cenarius': '塞纳里奥的梦境',
      'pulverize': '粉碎',
      'lacerate': '割伤',
      'incarnation': '化身',
      'thrash_bear': '痛击（熊）',
      'mangle': '裂伤',
      'wild_charge': '野性冲锋',
      'displacer_beast': '野性位移',
      'dash': '疾奔',
      'rake': '斜掠',
      'prowl': '潜行',
      'shadowmeld': '影遁',
      'force_of_nature': '自然之力',
      'trinket': '饰品',
      'potion': '合剂',
      'tigers_fury': '猛虎之怒',
      'omen_of_clarity': '清晰预兆',
      'bloodtalons': '血腥爪击',
      'king_of_the_jungle': '丛林之王',
      'ferocious_bite': '凶猛嘶咬',
      'rip': '割裂',
      'predatory_swiftness': '掠食者的迅捷',
      'savage_roar': '野蛮咆哮',
      'thrash_cat': '痛击（猫）',
      'persistent_multiplier': '持续因数',
      'moonfire_cat': '月火术（猫）',
      'swipe': '横扫',
      'shred': '撕碎',
      'starsurge': '星涌术',
      'lunar_empowerment': '月光强化',
      'solar_empowerment': '日光强化',
      'charges': '充能',
      'celestial_alignment': '超凡之盟',
      'sunfire': '阳炎术',
      'solar_peak': '日之巅',
      'stellar_flare': '星辰耀斑',
      'moonfire': '月火术',
      'lunar_peak': '月之巅',
      'wrath': '愤怒',
      'starfire': '星火术',
      'starfall': '星辰坠落',
    }
  },];

Map<String,String> AllSpells = {
  'bloodlust': '嗜血', //（英勇）
  'blood_fury': '狂怒',//（兽人）
  'arcane_torrent': '奥术洪流',//（血精灵）
  'berserking': '狂暴',//（巨魔）
  'potion': '合剂',
};

Map<String,int> AllBuffs = {
  'focus_fire': 82692,
  'bloodlust': 2825,
  'pre_steady_focus': 2825,
  'thrill_of_the_hunt': 2825,
  'bestial_wrath': 2825,
  'beast_cleave': 2825,
};
